### ISSUE TITLE
Handle task name interpolation

### ISSUE THREAD

**Issue by louisquentinjoucla** [mhansen/ansible-trace#16]
Hi everyone :wave: ,

With Ansible you are able to interpolate task name in certain circumstances.
One is when you use `include_tasks`, you are able to interpolate your tasks name in the included file like the following:
```yaml
---

- name: "Echo {{ include_message }}"
  shell: "echo {{ include_message }}"
```

Unfortunately the task name is not yet interpolated in hook `v2_runner_on_start` for linear strategy, which cause `B` event to have  a different name than the `E` event. As the E & B events name differs, the end is not catch, here is an example:

![image](https://user-images.githubusercontent.com/28892335/173269627-794e11cc-be26-48ff-bd5a-1c1b0e250cbe.png)

Fortunately `v2_playbook_on_task_start` hook (which is triggered before  `v2_runner_on_start`) returns the interpolated name. We could use that.

**Comment by mhansen** [comment]
Oh, neat. Thanks for spotting this, yes let's get this fixed.
