### ISSUE TITLE
Add top-level spans per play

### ISSUE THREAD

**Issue by mhansen** [mhansen/ansible-trace#3]
These would need to be kept track of per-host for the `free` strategy.

**Comment by louisquentinjoucla** [comment]
Hey !

Working on this issue, here is one of my test of how it would look like:
![image](https://user-images.githubusercontent.com/28892335/173494685-3ed3ce3d-b3e3-44e2-bbff-65763d6fda4b.png)

Correct me If I'm wrong, but I don't think strategy have an impact on trace span, as strategy are restricted per play. So no matter what is the strategy, all hosts are going to wait the end of a play for everyone before starting a new play

**Comment by mhansen** [comment]
> Correct me If I'm wrong, but I don't think strategy have an impact on trace span, as strategy are restricted per play. So no matter what is the strategy, all hosts are going to wait the end of a play for everyone before starting a new play.

I think you might be right here. I might have misread what the `free` strategy does, where `free` doesn't actually complete the next play until the last play is done for everyone.
